main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /main

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /backend
    #type:     annotation

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /frontend

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

