# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        MainBundle\Entity\User: sha512

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    foo: { password: test }
        usuario_log:
            entity:
                class: MainBundle:User
                property: username

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: usuario_log
            form_login:
                #csrf_provider: form.csrf_provider
                login_path: main_security_login #frontend_default_index
                check_path: main_security_login_check
                default_target_path: backend_default_index #backend_default_login_validation
            logout:
                path: main_security_logout
                target: main_security_login #
            remember_me:
                secret:   '%secret%'
                lifetime: 31536000 # 365 days in seconds - 31536000
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/main/security/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/, role: ROLE_BACKEND_ACCESS }
        - { path: ^/, role: ROLE_USER }



#        - { path: ^/backend, role: [ROLE_BACKEND_ACCESS], methods: [POST, PUT] }

        #USER
#        - { path: ^/backend/user$, role: [ROLE_USER], methods: [POST, PUT] }


            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

