<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigurationEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationEmailRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy([], ['idIncrement' => 'DESC']);
    }

    public function findActive()
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT configuration
            FROM MainBundle:ConfigurationEmail configuration
            ORDER BY configuration.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setMaxResults(1);

        return $query->getOneOrNullResult();
    }

    public function deleteAll()
    {
        $em = $this->getEntityManager();
        $dql = "DELETE MainBundle:ConfigurationEmail";

        $query = $em->createQuery($dql);

        return $query->execute();
    }

}
