<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementRepository extends EntityRepository
{


    public function findAll()
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT element
            FROM MainBundle:Element element
            WHERE
            element.status = :status
            ORDER BY element.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);

        return $query->getResult();
    }

    public function findOneById($id)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT element
            FROM MainBundle:Element element
            WHERE
            element.idIncrement = :id AND
            element.status = :status
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }


}
