<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FloorPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FloorPlanRepository extends EntityRepository
{

    public function findAll()
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT floorPlan
            FROM MainBundle:FloorPlan floorPlan
            WHERE
            floorPlan.status = :status
            ORDER BY floorPlan.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);

        return $query->getResult();
    }

    public function findOneById($id)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT floorPlan
            FROM MainBundle:FloorPlan floorPlan
            WHERE
            floorPlan.idIncrement = :id AND
            floorPlan.status = :status
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }

    public function findOneByEvent($event)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT floorPlan
            FROM MainBundle:FloorPlan floorPlan
            WHERE
            floorPlan.event = :event AND
            floorPlan.status = :status
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);
        $query->setParameter('event', $event);

        return $query->getOneOrNullResult();
    }


}
