<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{

    public function findAllPublished()
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT news
            FROM MainBundle:News news
            WHERE
            news.newsStatus = :newsStatus AND
            news.status = :status
            ORDER BY news.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);
        $query->setParameter('newsStatus', 'published');

        return $query->getResult();
    }

    public function findAll()
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT news
            FROM MainBundle:News news
            WHERE
            news.status = :status
            ORDER BY news.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);

        return $query->getResult();
    }

    public function findOneById($id)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT news
            FROM MainBundle:News news
            WHERE
            news.idIncrement = :id AND
            news.newsStatus = :newsStatus AND
            news.status = :status
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);
        $query->setParameter('newsStatus', 'published');
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }

    public function findPublishedNewsLimit($maxResults)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT news
            FROM MainBundle:News news
            WHERE
            news.newsStatus = :newsStatus AND
            news.status = :status
            ORDER BY news.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);
        $query->setParameter('newsStatus', 'published');
        $query->setMaxResults($maxResults);

        return $query->getResult();
    }


}
