<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array('status' => true), array('idIncrement' => 'DESC'));
    }

    public function findAllPublic()
    {
        return $this->findBy(array('status' => true, 'access' => 'public'), array('idIncrement' => 'DESC'));
    }

    public function findOneById($id)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT video
            FROM MainBundle:Video video
            WHERE
            video.idIncrement = :id AND
            video.status = :status
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }
    
    public function findPublicVideoLimit($maxResults)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT video
            FROM MainBundle:Video video
            WHERE
            video.status = :status AND
            video.access = :access
            ORDER BY video.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);
        $query->setParameter('access', 'public');
        $query->setMaxResults($maxResults);

        return $query->getResult();
    }

    public function findAllVideoLimit($maxResults)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT video
            FROM MainBundle:Video video
            WHERE
            video.status = :status
            ORDER BY video.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);
        $query->setMaxResults($maxResults);

        return $query->getResult();
    }



}
